name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Certifique-se de que o diretório 'dist' exista
      - name: Criar diretório de saída
        run: mkdir -p dist

      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jvfaria-dev
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Verificar se o arquivo SVG foi criado corretamente
      - name: Verificar arquivo SVG
        run: |
          if [ ! -f dist/github-contribution-grid-snake.svg ]; then
            echo "Erro: O arquivo SVG não foi gerado corretamente."
            exit 1
          fi

      # Push para o GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
